name       : wireless-regdb
version    : 2018.10.24
release    : 1
source     :
    - https://mirrors.edge.kernel.org/pub/software/network/wireless-regdb/wireless-regdb-2018.10.24.tar.xz : 0d3e845ac77d21aac9b88642c3dd043a83e3920d706b63d5e5c31dffdbec9116
license    : ISC
component  : system.base
summary    : This package contains the wireless regulatory database used by all cfg80211 based Linux wireless drivers.
description: |
    This package contains the wireless regulatory database used by all cfg80211 based Linux wireless drivers.
builddeps  :
    - gcc
install    : |
    %make_install
