name       : wireless-regdb
version    : 2020.04.29
release    : 2
source     :
    - https://mirrors.edge.kernel.org/pub/software/network/wireless-regdb/wireless-regdb-2020.04.29.tar.xz : 89fd031aed5977c219a71501e144375a10e7c90d1005d5d086ea7972886a2c7a
license    : ISC
component  : system.base
summary    : This package contains the wireless regulatory database used by all cfg80211 based Linux wireless drivers.
description: |
    This package contains the wireless regulatory database used by all cfg80211 based Linux wireless drivers.
install    : |
    %make_install
